version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ管理界面端口
      - "5672:5672"    # RabbitMQ通信端口
    environment:
      RABBITMQ_DEFAULT_USER: chat
      RABBITMQ_DEFAULT_PASS: chat

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: chat
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"