spring:
  application:
    name: easy-chat
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    generate-ddl: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 3000
server:
  port: ${SERVER_PORT}
tencent:
  message:
    secret-id: ${MESSAGE_TENCENT_SECRET_ID}
    secret-key: ${MESSAGE_TENCENT_SECRET_KEY}
    template-id: ${MESSAGE_TENCENT_TEMPLATE_ID}
    sms-sdk-app-id: ${MESSAGE_TENCENT_SDK_APP_ID}
    sign-name: ${MESSAGE_TENCENT_SIGN_NAME}
  cos:
    app-id: ${COS_ID}
    bucket-name: ${COS_BUCKET}
    region-id: ${COS_REGION}
    secret-id: ${COS_SECRET_ID}
    secret-key: ${COS_SECRET_KEY}
    base-url: ${COS_BASE_URL}